project:
  type: website

website:
  title: "SIPBS Internships"
  site-url: https://sipbs-compbiol.github.io/sipbs-internships
  description: "Course website for SIPBS Internships and Matching in Semester 1 2023"
  favicon: "icon_32.png"
  navbar:
    logo: ./assets/images/sipbs_compbio.png
    right:
      - text: "Home"
        file: index.qmd
      - text: "General Information"
        menu:
        - text: "What is an Internship?"
          href: internships.qmd
        - text: "Matching"
          href: matching.qmd
        - text: "Current Projects"
          href: projects/2023-24.qmd
        - text: "External Funding Opporunities"
          href: external_funding.qmd
      - text: "Materials"
        menu: 
        - text: "Slides"
          href: slides.qmd
        - text: "Previous Projects"
          href: previous_projects.qmd
        - text: "Forms"
          href: forms.qmd
      - icon: github
        href: https://github.com/sipbs-compbiol/sipbs-internships
      - icon: twitter
        href: https://twitter.com/scompbiol
      - icon: rss
        href: index.xml  
  page-footer: 
    left: This site © University of Strathclyde 2023

format:
  html:
    theme: simplex
    toc: true
    css: styles.css
    embed-resources: true

editor: visual

execute:
  freeze: auto