---
title: "External Funding Opportunities"
description: |
 Organisations and programmes that might offer funding for summer studentships
number-sections: true
about:
  template: marquee
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/scompbiol
    - icon: github
      text: Github
      href: https://github.com/sipbs-compbiol
    - icon: envelope
      text: Email
      href: mailto:leighton.pritchard@strath.ac.uk
html:
  anchor-sections: true
---

Some opportunities for internship funding are listed below.

::: callout-important
Please read the documentation for these funding sources carefully. Many sources have specific requirements for applicants (e.g. supervisor or student may need to be a learned society member; age, qualification, nationality, or other restrictions may apply).
:::

::: callout-note
Some funders require the supervisor to apply, some require the student to apply, and some ask for a joint application.
:::

::: callout-warning
It is the responsibility of the supervisor and/or student to apply for, and to manage, any funding.
:::

::: callout-important
This is **not** an exhaustive or complete list.
:::

## Strathclyde

-   Interns\@Strathclyde: <https://www.strath.ac.uk/studywithus/scholarships/researchinternsstrathclyde/>

## General

-   Carnegie Trust: <https://www.carnegie-trust.org/award-schemes/vacation-scholarships/>
-   Gatsby: <https://www.gatsby.org.uk/plant-science/programmes/sainsbury-undergraduate-studentships>
-   Saltire Internships: <https://www.entrepreneurialscotland.com/2023-apply-now>
-   Wellcome Trust: <https://wellcome.ac.uk/grant-funding/schemes/biomedical-vacation-scholarships>

## Learned Society

-   Animal Free Research: <https://www.animalfreeresearchuk.org/summerstudent/programme/>
-   Association for the Study of Animal Behaviour: <https://asab.squarespace.com/scholarships/>
-   British Mycological Society: <https://www.rsb.org.uk/get-involved/grants/undergraduate-studentships>
-   British Society for Cell Biology: <https://bscb.org/competitions-awardsgrants/studentships/>
-   Biochemical Society: <https://www.biochemistry.org/grants-and-awards/grants-and-bursaries/summer-vacation-studentships/>
-   Experimental Psychology Society: <https://eps.ac.uk/undergraduate-research-bursary/>
-   FRAME: <https://frame.org.uk/what-we-do/summer-studentship-programme/>
-   The Genetics Society: <https://genetics.org.uk/grants/summer-studentships/>
-   Medical Research Scotland: <https://medicalresearchscotland.org.uk/undergraduate-vacation-scholarship/>
-   Microbiology Society: <https://microbiologysociety.org/grants/travel-research/harry-smith-vacation-studentships.html>
-   Physiological Society: <https://www.physoc.org/grants-and-prizes/grants/research-springboard-studentship/>
-   Royal Microscopical Society: <https://www.rms.org.uk/opportunities/summer-studentships.html>
-   Society for Applied Microbiology: <https://sfam.org.uk/career/grants/summer-student-placement-scholarship.html>
-   Society for Endocrinology: <https://www.endocrinology.org/grants-and-awards/research-grants/summer-studentships/>

## Other Resources

-   [Internships listed at the British Neuroscience Association](https://www.bna.org.uk/careers/undergraduate-summer-research-placements/)
-   [Internships listed at the Royal Society of Biology](https://www.rsb.org.uk/get-involved/grants/undergraduate-studentships)
