---
title: "What is an Internship?"
description: |
 What an internship is and how it can help
number-sections: true
about:
  template: marquee
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/scompbiol
    - icon: github
      text: Github
      href: https://github.com/sipbs-compbiol
    - icon: envelope
      text: Email
      href: mailto:leighton.pritchard@strath.ac.uk
html:
  anchor-sections: true
---

This page aims to describe what an internship, how it might be useful for your future career and other ambitions, and to give answers to some other related questions.

## What is an internship?

An internship is a period of professional work experience. In the case of the SIPBS matching scheme, this is typically an 8-10 week summer placement in a working research laboratory within the department.

::: { .callout-note }
The Careers Service has support to help with finding a placement/internship outwith the SIPBS matching scheme.

- [Careers Service Internship and Placement Advice](https://www.strath.ac.uk/professionalservices/careers/students/workexperience/internshipsplacements/)
:::

::: {.callout-warning}
**It is very important for you to take responsibility for your own internship search.**

As the Careers Service advises,

> “Source your own internship & placement: It's very important to be proactive in your job search. Do not wait for vacancies to be advertised - it might never happen. Many organisations do not need to advertise their work experience opportunities, as they receive hundreds of speculative applications from students.”

If you wait to be noticed by someone and offered an internship, you will most likely not get one.
:::

## Will I be paid?

Internships may be paid, unpaid, or partially-paid (e.g. the student may receive a stipend for the period, rather than an hourly rate).

The SIPBS matching scheme provides no funds either for the student, or in support of the project. Supervisors who offer projects may have financial resources that could be used to fund the project or pay the intern. Alternatively the student or the supervisor (or both together, depending on the scheme) may apply for funding from a third party, such as the university, a charity, or professional society, to support the placement.

## What will I get from the experience?

By engaging in a practical research project, you will obtain skills, knowledge, and experience that cannot be obtained in other ways. You will be able to establish professional connections and begin to network in the field, as well as contributing to finding answers to real, cutting-edge research questions.

If you think you might be interested in a research career, then a placement is one way to find out if that career path is something you might like.

Where placements, or their funding, are competitive, there may be an element of prestige to winning that funding which helps make your future CV stand out against other applicants'.

## What kinds of project might I be able to do?

::: callout-note
The range of projects and supervisors varies year-by-year, and you are always free to approach supervisors at other universities or in industry to find a project that suits you.
:::

Please take a look at the [Previous Projects](./previous_projects.qmd) page to see what projects have been on offer previously. General areas in which projects have been offered within SIPBS include:

-   Cellular Basis of Disease
    -   Cancer
    -   Inflammatory disease
    -   Cardiovascular and metabolic disease
    -   Neuroscience and mental health
-   Computational Biology and Bioinformatics
    -   Metabolic modelling of heart cells
    -   Reconstructing regulatory networks in bacteria
-   Industrial Biotechnology
-   Microbiology
-   Pharmaceutical Sciences
-   Pharmacoepidemiology and Health Care

## Do I have to use the SIPBS matching scheme?

::: { .callout-tip }
No. You are always free to obtain an internship independently of the SIPBS scheme.
:::

We offer the scheme to simplify the process of matching interested students with supervisors who are thinking of offering projects. As there are usually fewer projects on offer than interested students, we need to manage this process. But if you are interested in working in a particular area, or with a particular group, there is no reason you should not approach potential supervisors directly, outwith this scheme.

::: { .callout-warning }
The scheme we run at SIPBS is unusual for internships/placements, in that we advertise and try to match students with projects.

**Most internships are never advertised,** you need to **be proactive** and ask people or organisations you might want to work with if they may have opportunities.
:::

::: {.callout-important}
The university has pages offering advice for arranging your own internship:

- [Work experience and internship placements](https://www.strath.ac.uk/professionalservices/careers/students/workexperience/internshipsplacements/)
- [Making speculative applications for internships](https://www.strath.ac.uk/professionalservices/careers/students/makingapplications/makingspeculativeapplications/)
:::
